const rankings = [
  { name: 'Zem01', wins: 10, draws: 0, losses: 2 },
  { name: 'Lahana Turşusu', wins: 8, draws: 0, losses: 3 },
  { name: 'Edmir04', wins: 8, draws: 0, losses: 3 },
  { name: 'Rebell', wins: 5, draws: 0, losses: 1 },
  { name: 'ANNOYIING', wins: 6, draws: 0, losses: 3 },
  { name: 'vPaiinXz', wins: 3, draws: 0, losses: 0 },
  { name: 'CruqZzy', wins: 3, draws: 0, losses: 1 },
  { name: 'Yasin_78a', wins: 2, draws: 0, losses: 0 },
  { name: 'Arezmaa', wins: 4, draws: 0, losses: 3 },
  { name: 'FuriUFC', wins: 3, draws: 0, losses: 2 },
  { name: 'Carnalito61', wins: 2, draws: 0, losses: 1 },
  { name: 'Mete', wins: 1, draws: 0, losses: 1 },
  { name: 'Cem', wins: 1, draws: 0, losses: 1 },
  { name: 'henzla', wins: 1, draws: 0, losses: 1 },
  { name: 'zFreezy', wins: 4, draws: 0, losses: 5 },
  { name: 'mukadderat', wins: 2, draws: 0, losses: 2 },
  { name: 'Bronxs_MMA', wins: 2, draws: 0, losses: 3 },
  { name: 'Seyiito', wins: 3, draws: 0, losses: 5 },
  { name: 'RushMMA', wins: 2, draws: 0, losses: 5 },
  { name: 'Simouny', wins: 2, draws: 0, losses: 5 },
  { name: 'thegame2621', wins: 1, draws: 0, losses: 4 },
  { name: 'alpi', wins: 1, draws: 0, losses: 7 },
  { name: 'TyT-3RR0B', wins: 0, draws: 0, losses: 1 },
  { name: 'Haci OnFire VM', wins: 0, draws: 0, losses: 1 },
  { name: 'pulle30', wins: 0, draws: 0, losses: 2 },
  { name: 'Poatan209', wins: 0, draws: 0, losses: 3 },
  { name: 'eren_azz', wins: 0, draws: 0, losses: 3 },
  // { name: 'Wasiyamato', wins: 0, draws: 0, losses: 1 },
  // { name: 'Atilla', wins: 0, draws: 0, losses: 1 },
  // { name: 'AlpiQLF', wins: 0, draws: 0, losses: 2 },
  // { name: 'Adam', wins: 0, draws: 0, losses: 3 },
  // { name: 'Ronaldinho', wins: 0, draws: 0, losses: 4 },
];

const players = [
  'Zem01',
  'CruqZzy',
  'Cem',
  'ANNOYIING',
  'vPaiinXz',
  'henzla',
  'Poatan_209',
  'Edmir',
  'mukadderat',
  'RushMMA',
  'Yasin_87a',
  'thegame2621',
  'pulle30',
  'Lahana Turşusu',
  'eren_azz',
  'alpi',
  'Freezy',
  'TyT-3RROB',
  'Meteツ',
  'Haci',
];

// export both rankings and players
module.exports = { rankings, players };
