const rankings = [
    {name: "Zem01", wins: 8, draws: 0, losses: 2},
    {name: "Lahana Turşusu", wins: 7, draws: 0, losses: 2},
    {name: "Rebell", wins: 5, draws: 0, losses: 1},
    {name: "Edmir04", wins: 6, draws: 0, losses: 3},
    {name: "ANNOYIING", wins: 4, draws: 0, losses: 2},
    {name: "FuriUFC", wins: 3, draws: 0, losses: 1},
    {name: "Arezmaa", wins: 4, draws: 0, losses: 3},
    {name: "CruqZzy", wins: 1, draws: 0, losses: 0},
    {name: "zFreezy", wins: 4, draws: 0, losses: 4},
    {name: "Bronxs_MMA", wins: 2, draws: 0, losses: 2},
    {name: "Carnalito61", wins: 1, draws: 0, losses: 1},
    {name: "RushMMA", wins: 2, draws: 0, losses: 4},
    {name: "Simouny", wins: 2, draws: 0, losses: 4},
    {name: "Seyiito", wins: 2, draws: 0, losses: 4},
    {name: "thegame2621", wins: 1, draws: 0, losses: 4},
    {name: "alpi", wins: 1, draws: 0, losses: 6},
    {name: "eren_azz", wins: 0, draws: 0, losses: 1},
    {name: "mukadderat", wins: 0, draws: 0, losses: 1},
    {name: "AlpiQLF", wins: 0, draws: 0, losses: 1},
    {name: "Atilla", wins: 0, draws: 0, losses: 1},
    {name: "Poatan209", wins: 0, draws: 0, losses: 2},
    {name: "Adam", wins: 0, draws: 0, losses: 3},
    {name: "Ronaldinho", wins: 0, draws: 0, losses: 4}
];

const players = [
    'Zem01',
    'Lahana Turşusu',
    'ANNOYIING',
    'CruqZzy',
    'Mukadderat',
    'Simouny',
    'Seyiito',
    'AlpiQLF',
    'Yasin_87a',
    'eren_azz',
    // 'Rebell',
    // 'Edmir04',
    // 'Arezmaa',
    // 'RushMMA',
    // 'Freezy',
    // 'Poatan209',
    // 'Carnalito61',
    // 'thegame2621',
    // 'alpi',
    // 'Bronxs_MMA',
    // 'FuriUFC',
];

// export both rankings and players
module.exports = {rankings, players};