const rankings = [
  { name: 'Zem01', wins: 9, draws: 0, losses: 2 },
  { name: 'Rebell', wins: 5, draws: 0, losses: 1 },
  { name: 'Lahana Turşusu', wins: 7, draws: 0, losses: 3 },
  { name: 'Edmir04', wins: 7, draws: 0, losses: 3 },
  { name: 'CruqZzy', wins: 3, draws: 0, losses: 0 },
  { name: 'ANNOYIING', wins: 5, draws: 0, losses: 3 },
  { name: 'Arezmaa', wins: 4, draws: 0, losses: 3 },
  { name: 'FuriUFC', wins: 3, draws: 0, losses: 2 },
  { name: 'Yasin_78a', wins: 1, draws: 0, losses: 0 },
  { name: 'Cem', wins: 1, draws: 0, losses: 0 },
  { name: 'henzla', wins: 1, draws: 0, losses: 0 },
  { name: 'zFreezy', wins: 4, draws: 0, losses: 4 },
  { name: 'Bronxs_MMA', wins: 2, draws: 0, losses: 2 },
  { name: 'Carnalito61', wins: 1, draws: 0, losses: 1 },
  { name: 'mukadderat', wins: 1, draws: 0, losses: 2 },
  { name: 'Seyiito', wins: 3, draws: 0, losses: 5 },
  { name: 'RushMMA', wins: 2, draws: 0, losses: 4 },
  { name: 'Simouny', wins: 2, draws: 0, losses: 5 },
  { name: 'thegame2621', wins: 1, draws: 0, losses: 4 },
  { name: 'alpi', wins: 1, draws: 0, losses: 7 },
  { name: 'Wasiyamato', wins: 0, draws: 0, losses: 1 },
  { name: 'TyT-3RROB', wins: 0, draws: 0, losses: 1 },
  { name: 'Atilla', wins: 0, draws: 0, losses: 1 },
  { name: 'eren_azz', wins: 0, draws: 0, losses: 2 },
  { name: 'Poatan209', wins: 0, draws: 0, losses: 2 },
  { name: 'AlpiQLF', wins: 0, draws: 0, losses: 2 },
  { name: 'Adam', wins: 0, draws: 0, losses: 3 },
  { name: 'Ronaldinho', wins: 0, draws: 0, losses: 4 },
];

const players = [
  'FuriUFC',
  'CruqZzy',
  'ANNOYIING',
  'Seyiito',
  'Mukadderat',
  'Edmir04',
  'alpi',
  'Cem',
  'Freezy',
  'thegame2621',
  'Yasin_87a',
  'eren_azz',
  'henzla',
  'TyT-3RROB',
  'Mete',
  'pulle30',
  // 'Simouny',
  // 'AlpiQLF',
  // 'Zem01',
  // 'Lahana Turşusu',
  // 'Rebell',
  // 'Arezmaa',
  // 'RushMMA',
  // 'Poatan209',
  // 'Carnalito61',
  // 'Bronxs_MMA',
];

// export both rankings and players
module.exports = { rankings, players };
